#define __NV_CUBIN_HANDLE_STORAGE__ static
#include "crt/host_runtime.h"
#include "kernels.fatbin.c"
typedef SumReduceOperation<int>  _Z18SumReduceOperationIiE;
typedef DFISharedPositionSetter<int>  _Z23DFISharedPositionSetterIiE;
typedef DefaultSharedPositionSetter<int>  _Z27DefaultSharedPositionSetterIiE;
typedef MaxReduceOperation<int>  _Z18MaxReduceOperationIiE;
typedef NonCastNormalizeMatrixOperation<int, float>  _Z31NonCastNormalizeMatrixOperationIifE;
typedef CastNormalizeMatrixOperation<int, float>  _Z28CastNormalizeMatrixOperationIifE;
typedef NonCastNormalizeMatrixOperation<int, double>  _Z31NonCastNormalizeMatrixOperationIidE;
typedef CastNormalizeMatrixOperation<int, double>  _Z28CastNormalizeMatrixOperationIidE;
static void __device_stub__Z15multiple_reduceIi18SumReduceOperationIiE23DFISharedPositionSetterIiEEvPT_S5_iiT0_T1_(int *, int *, int, int,  _Z18SumReduceOperationIiE&,  _Z23DFISharedPositionSetterIiE&);
static void __device_stub__Z17multiple_reduce_2Ii18SumReduceOperationIiE27DefaultSharedPositionSetterIiEEvPT_iiT0_T1_(int *, int, int,  _Z18SumReduceOperationIiE&,  _Z27DefaultSharedPositionSetterIiE&);
static void __device_stub__Z15multiple_reduceIi18MaxReduceOperationIiE27DefaultSharedPositionSetterIiEEvPT_S5_iiT0_T1_(int *, int *, int, int,  _Z18MaxReduceOperationIiE&,  _Z27DefaultSharedPositionSetterIiE&);
static void __device_stub__Z17multiple_reduce_2Ii18MaxReduceOperationIiE27DefaultSharedPositionSetterIiEEvPT_iiT0_T1_(int *, int, int,  _Z18MaxReduceOperationIiE&,  _Z27DefaultSharedPositionSetterIiE&);
static void __device_stub__Z18multiple_normalizeIif31NonCastNormalizeMatrixOperationIifEEvPT0_PT_S5_iiiT1_(float *, int *, int *, int, int, int,  _Z31NonCastNormalizeMatrixOperationIifE&);
static void __device_stub__Z18multiple_normalizeIif28CastNormalizeMatrixOperationIifEEvPT0_PT_S5_iiiT1_(float *, int *, int *, int, int, int,  _Z28CastNormalizeMatrixOperationIifE&);
static void __device_stub__Z18multiple_normalizeIid31NonCastNormalizeMatrixOperationIidEEvPT0_PT_S5_iiiT1_(double *, int *, int *, int, int, int,  _Z31NonCastNormalizeMatrixOperationIidE&);
static void __device_stub__Z18multiple_normalizeIid28CastNormalizeMatrixOperationIidEEvPT0_PT_S5_iiiT1_(double *, int *, int *, int, int, int,  _Z28CastNormalizeMatrixOperationIidE&);
static void __nv_cudaEntityRegisterCallback(void **);
static void __sti____cudaRegisterAll_15_kernels_cpp1_ii_1d9aa1d2(void) __attribute__((__constructor__));
static void __device_stub__Z15multiple_reduceIi18SumReduceOperationIiE23DFISharedPositionSetterIiEEvPT_S5_iiT0_T1_(int *__par0, int *__par1, int __par2, int __par3,  _Z18SumReduceOperationIiE&__par4,  _Z23DFISharedPositionSetterIiE&__par5){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 16UL);__cudaSetupArgSimple(__par3, 20UL);__cudaSetupArg(__par4, 24UL);__cudaSetupArg(__par5, 25UL);__cudaLaunch(((char *)((void ( *)(int *, int *, int, int,  _Z18SumReduceOperationIiE,  _Z23DFISharedPositionSetterIiE))multiple_reduce<int, SumReduceOperation<int> , DFISharedPositionSetter<int> > )));}
template<> __specialization_static void __wrapper__device_stub_multiple_reduce<int, ::SumReduceOperation<int> , ::DFISharedPositionSetter<int> >( int *&__cuda_0,int *&__cuda_1,int &__cuda_2,int &__cuda_3, _Z18SumReduceOperationIiE &__cuda_4, _Z23DFISharedPositionSetterIiE &__cuda_5){__device_stub__Z15multiple_reduceIi18SumReduceOperationIiE23DFISharedPositionSetterIiEEvPT_S5_iiT0_T1_( __cuda_0,__cuda_1,__cuda_2,__cuda_3,__cuda_4,__cuda_5);}
static void __device_stub__Z17multiple_reduce_2Ii18SumReduceOperationIiE27DefaultSharedPositionSetterIiEEvPT_iiT0_T1_(int *__par0, int __par1, int __par2,  _Z18SumReduceOperationIiE&__par3,  _Z27DefaultSharedPositionSetterIiE&__par4){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 12UL);__cudaSetupArg(__par3, 16UL);__cudaSetupArg(__par4, 17UL);__cudaLaunch(((char *)((void ( *)(int *, int, int,  _Z18SumReduceOperationIiE,  _Z27DefaultSharedPositionSetterIiE))multiple_reduce_2<int, SumReduceOperation<int> , DefaultSharedPositionSetter<int> > )));}
template<> __specialization_static void __wrapper__device_stub_multiple_reduce_2<int, ::SumReduceOperation<int> , ::DefaultSharedPositionSetter<int> >( int *&__cuda_0,int &__cuda_1,int &__cuda_2, _Z18SumReduceOperationIiE &__cuda_3, _Z27DefaultSharedPositionSetterIiE &__cuda_4){__device_stub__Z17multiple_reduce_2Ii18SumReduceOperationIiE27DefaultSharedPositionSetterIiEEvPT_iiT0_T1_( __cuda_0,__cuda_1,__cuda_2,__cuda_3,__cuda_4);}
static void __device_stub__Z15multiple_reduceIi18MaxReduceOperationIiE27DefaultSharedPositionSetterIiEEvPT_S5_iiT0_T1_(int *__par0, int *__par1, int __par2, int __par3,  _Z18MaxReduceOperationIiE&__par4,  _Z27DefaultSharedPositionSetterIiE&__par5){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 16UL);__cudaSetupArgSimple(__par3, 20UL);__cudaSetupArg(__par4, 24UL);__cudaSetupArg(__par5, 25UL);__cudaLaunch(((char *)((void ( *)(int *, int *, int, int,  _Z18MaxReduceOperationIiE,  _Z27DefaultSharedPositionSetterIiE))multiple_reduce<int, MaxReduceOperation<int> , DefaultSharedPositionSetter<int> > )));}
template<> __specialization_static void __wrapper__device_stub_multiple_reduce<int, ::MaxReduceOperation<int> , ::DefaultSharedPositionSetter<int> >( int *&__cuda_0,int *&__cuda_1,int &__cuda_2,int &__cuda_3, _Z18MaxReduceOperationIiE &__cuda_4, _Z27DefaultSharedPositionSetterIiE &__cuda_5){__device_stub__Z15multiple_reduceIi18MaxReduceOperationIiE27DefaultSharedPositionSetterIiEEvPT_S5_iiT0_T1_( __cuda_0,__cuda_1,__cuda_2,__cuda_3,__cuda_4,__cuda_5);}
static void __device_stub__Z17multiple_reduce_2Ii18MaxReduceOperationIiE27DefaultSharedPositionSetterIiEEvPT_iiT0_T1_(int *__par0, int __par1, int __par2,  _Z18MaxReduceOperationIiE&__par3,  _Z27DefaultSharedPositionSetterIiE&__par4){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 12UL);__cudaSetupArg(__par3, 16UL);__cudaSetupArg(__par4, 17UL);__cudaLaunch(((char *)((void ( *)(int *, int, int,  _Z18MaxReduceOperationIiE,  _Z27DefaultSharedPositionSetterIiE))multiple_reduce_2<int, MaxReduceOperation<int> , DefaultSharedPositionSetter<int> > )));}
template<> __specialization_static void __wrapper__device_stub_multiple_reduce_2<int, ::MaxReduceOperation<int> , ::DefaultSharedPositionSetter<int> >( int *&__cuda_0,int &__cuda_1,int &__cuda_2, _Z18MaxReduceOperationIiE &__cuda_3, _Z27DefaultSharedPositionSetterIiE &__cuda_4){__device_stub__Z17multiple_reduce_2Ii18MaxReduceOperationIiE27DefaultSharedPositionSetterIiEEvPT_iiT0_T1_( __cuda_0,__cuda_1,__cuda_2,__cuda_3,__cuda_4);}
static void __device_stub__Z18multiple_normalizeIif31NonCastNormalizeMatrixOperationIifEEvPT0_PT_S5_iiiT1_(float *__par0, int *__par1, int *__par2, int __par3, int __par4, int __par5,  _Z31NonCastNormalizeMatrixOperationIifE&__par6){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 16UL);__cudaSetupArgSimple(__par3, 24UL);__cudaSetupArgSimple(__par4, 28UL);__cudaSetupArgSimple(__par5, 32UL);__cudaSetupArg(__par6, 36UL);__cudaLaunch(((char *)((void ( *)(float *, int *, int *, int, int, int,  _Z31NonCastNormalizeMatrixOperationIifE))multiple_normalize<int, float, NonCastNormalizeMatrixOperation<int, float> > )));}
template<> __specialization_static void __wrapper__device_stub_multiple_normalize<int,float, ::NonCastNormalizeMatrixOperation<int, float> >( float *&__cuda_0,int *&__cuda_1,int *&__cuda_2,int &__cuda_3,int &__cuda_4,int &__cuda_5, _Z31NonCastNormalizeMatrixOperationIifE &__cuda_6){__device_stub__Z18multiple_normalizeIif31NonCastNormalizeMatrixOperationIifEEvPT0_PT_S5_iiiT1_( __cuda_0,__cuda_1,__cuda_2,__cuda_3,__cuda_4,__cuda_5,__cuda_6);}
static void __device_stub__Z18multiple_normalizeIif28CastNormalizeMatrixOperationIifEEvPT0_PT_S5_iiiT1_(float *__par0, int *__par1, int *__par2, int __par3, int __par4, int __par5,  _Z28CastNormalizeMatrixOperationIifE&__par6){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 16UL);__cudaSetupArgSimple(__par3, 24UL);__cudaSetupArgSimple(__par4, 28UL);__cudaSetupArgSimple(__par5, 32UL);__cudaSetupArg(__par6, 36UL);__cudaLaunch(((char *)((void ( *)(float *, int *, int *, int, int, int,  _Z28CastNormalizeMatrixOperationIifE))multiple_normalize<int, float, CastNormalizeMatrixOperation<int, float> > )));}
template<> __specialization_static void __wrapper__device_stub_multiple_normalize<int,float, ::CastNormalizeMatrixOperation<int, float> >( float *&__cuda_0,int *&__cuda_1,int *&__cuda_2,int &__cuda_3,int &__cuda_4,int &__cuda_5, _Z28CastNormalizeMatrixOperationIifE &__cuda_6){__device_stub__Z18multiple_normalizeIif28CastNormalizeMatrixOperationIifEEvPT0_PT_S5_iiiT1_( __cuda_0,__cuda_1,__cuda_2,__cuda_3,__cuda_4,__cuda_5,__cuda_6);}
static void __device_stub__Z18multiple_normalizeIid31NonCastNormalizeMatrixOperationIidEEvPT0_PT_S5_iiiT1_(double *__par0, int *__par1, int *__par2, int __par3, int __par4, int __par5,  _Z31NonCastNormalizeMatrixOperationIidE&__par6){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 16UL);__cudaSetupArgSimple(__par3, 24UL);__cudaSetupArgSimple(__par4, 28UL);__cudaSetupArgSimple(__par5, 32UL);__cudaSetupArg(__par6, 36UL);__cudaLaunch(((char *)((void ( *)(double *, int *, int *, int, int, int,  _Z31NonCastNormalizeMatrixOperationIidE))multiple_normalize<int, double, NonCastNormalizeMatrixOperation<int, double> > )));}
template<> __specialization_static void __wrapper__device_stub_multiple_normalize<int,double, ::NonCastNormalizeMatrixOperation<int, double> >( double *&__cuda_0,int *&__cuda_1,int *&__cuda_2,int &__cuda_3,int &__cuda_4,int &__cuda_5, _Z31NonCastNormalizeMatrixOperationIidE &__cuda_6){__device_stub__Z18multiple_normalizeIid31NonCastNormalizeMatrixOperationIidEEvPT0_PT_S5_iiiT1_( __cuda_0,__cuda_1,__cuda_2,__cuda_3,__cuda_4,__cuda_5,__cuda_6);}
static void __device_stub__Z18multiple_normalizeIid28CastNormalizeMatrixOperationIidEEvPT0_PT_S5_iiiT1_(double *__par0, int *__par1, int *__par2, int __par3, int __par4, int __par5,  _Z28CastNormalizeMatrixOperationIidE&__par6){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 16UL);__cudaSetupArgSimple(__par3, 24UL);__cudaSetupArgSimple(__par4, 28UL);__cudaSetupArgSimple(__par5, 32UL);__cudaSetupArg(__par6, 36UL);__cudaLaunch(((char *)((void ( *)(double *, int *, int *, int, int, int,  _Z28CastNormalizeMatrixOperationIidE))multiple_normalize<int, double, CastNormalizeMatrixOperation<int, double> > )));}
template<> __specialization_static void __wrapper__device_stub_multiple_normalize<int,double, ::CastNormalizeMatrixOperation<int, double> >( double *&__cuda_0,int *&__cuda_1,int *&__cuda_2,int &__cuda_3,int &__cuda_4,int &__cuda_5, _Z28CastNormalizeMatrixOperationIidE &__cuda_6){__device_stub__Z18multiple_normalizeIid28CastNormalizeMatrixOperationIidEEvPT0_PT_S5_iiiT1_( __cuda_0,__cuda_1,__cuda_2,__cuda_3,__cuda_4,__cuda_5,__cuda_6);}
static void __nv_cudaEntityRegisterCallback(void **__T223){__nv_dummy_param_ref(__T223);__cudaRegisterEntry(__T223, ((void ( *)(double *, int *, int *, int, int, int,  _Z28CastNormalizeMatrixOperationIidE))multiple_normalize<int, double, CastNormalizeMatrixOperation<int, double> > ), _Z18multiple_normalizeIid28CastNormalizeMatrixOperationIidEEvPT0_PT_S5_iiiT1_, (-1));__cudaRegisterEntry(__T223, ((void ( *)(double *, int *, int *, int, int, int,  _Z31NonCastNormalizeMatrixOperationIidE))multiple_normalize<int, double, NonCastNormalizeMatrixOperation<int, double> > ), _Z18multiple_normalizeIid31NonCastNormalizeMatrixOperationIidEEvPT0_PT_S5_iiiT1_, (-1));__cudaRegisterEntry(__T223, ((void ( *)(float *, int *, int *, int, int, int,  _Z28CastNormalizeMatrixOperationIifE))multiple_normalize<int, float, CastNormalizeMatrixOperation<int, float> > ), _Z18multiple_normalizeIif28CastNormalizeMatrixOperationIifEEvPT0_PT_S5_iiiT1_, (-1));__cudaRegisterEntry(__T223, ((void ( *)(float *, int *, int *, int, int, int,  _Z31NonCastNormalizeMatrixOperationIifE))multiple_normalize<int, float, NonCastNormalizeMatrixOperation<int, float> > ), _Z18multiple_normalizeIif31NonCastNormalizeMatrixOperationIifEEvPT0_PT_S5_iiiT1_, (-1));__cudaRegisterEntry(__T223, ((void ( *)(int *, int, int,  _Z18MaxReduceOperationIiE,  _Z27DefaultSharedPositionSetterIiE))multiple_reduce_2<int, MaxReduceOperation<int> , DefaultSharedPositionSetter<int> > ), _Z17multiple_reduce_2Ii18MaxReduceOperationIiE27DefaultSharedPositionSetterIiEEvPT_iiT0_T1_, (-1));__cudaRegisterEntry(__T223, ((void ( *)(int *, int *, int, int,  _Z18MaxReduceOperationIiE,  _Z27DefaultSharedPositionSetterIiE))multiple_reduce<int, MaxReduceOperation<int> , DefaultSharedPositionSetter<int> > ), _Z15multiple_reduceIi18MaxReduceOperationIiE27DefaultSharedPositionSetterIiEEvPT_S5_iiT0_T1_, (-1));__cudaRegisterEntry(__T223, ((void ( *)(int *, int, int,  _Z18SumReduceOperationIiE,  _Z27DefaultSharedPositionSetterIiE))multiple_reduce_2<int, SumReduceOperation<int> , DefaultSharedPositionSetter<int> > ), _Z17multiple_reduce_2Ii18SumReduceOperationIiE27DefaultSharedPositionSetterIiEEvPT_iiT0_T1_, (-1));__cudaRegisterEntry(__T223, ((void ( *)(int *, int *, int, int,  _Z18SumReduceOperationIiE,  _Z23DFISharedPositionSetterIiE))multiple_reduce<int, SumReduceOperation<int> , DFISharedPositionSetter<int> > ), _Z15multiple_reduceIi18SumReduceOperationIiE23DFISharedPositionSetterIiEEvPT_S5_iiT0_T1_, (-1));}
static void __sti____cudaRegisterAll_15_kernels_cpp1_ii_1d9aa1d2(void){__cudaRegisterBinary(__nv_cudaEntityRegisterCallback);}
